package com.inspiredandroid.kai.linux

import android.content.Context
import io.ktor.client.HttpClient
import io.ktor.client.engine.okhttp.OkHttp
import kotlinx.coroutines.currentCoroutineContext
import kotlinx.coroutines.ensureActive
import kotlinx.coroutines.sync.Mutex
import java.io.File
import java.io.FileOutputStream

/** Where an install has got to, in terms both feature UIs can render. */
sealed interface InstallStep {
    data class Download(val fraction: Float) : InstallStep
    data object Extract : InstallStep
    data object Configure : InstallStep
    data class Packages(val packages: List<String>) : InstallStep
}

private const val UPDATE_TIMEOUT_SECONDS = 300L
private const val PACKAGE_TIMEOUT_SECONDS = 900L
private const val RUNTIME_PROBE_TIMEOUT_SECONDS = 30L

/** Debian 13 arm64 rootfs generated by scripts/build-debian-rootfs.sh. */
private const val EMBEDDED_ROOTFS_ASSET = "moataz-debian-rootfs-arm64-v13.tar.xz"

/**
 * Downloads, extracts and bootstraps a rootfs. The chat sandbox and Kai Build
 * both drive this; whoever gets there first produces the install the other one
 * then finds already present.
 */
class LinuxInstaller(
    private val paths: LinuxPaths,
    private val appContext: Context,
) {

    private val downloader = RootfsDownloader(HttpClient(OkHttp))

    /**
     * Installs [distro] into [paths] and returns the marker it wrote. A marker is
     * written only after native PRoot, distro identity and required CLI probes
     * all pass, so "Ready" means the environment can execute commands.
     */
    suspend fun install(distro: LinuxDistro, onStep: (InstallStep) -> Unit): InstallMarker {
        val spec = DistroSpec.of(distro)
        paths.ensureLayout()
        paths.validateNativeRuntime()

        paths.deleteInstall()
        paths.ensureLayout()

        val archive = paths.archiveFile(spec)
        try {
            val hasEmbeddedAsset = copyEmbeddedAsset(spec, archive)
            if (!hasEmbeddedAsset) {
                onStep(InstallStep.Download(0f))
                downloader.download(spec.rootfsUrls(), archive) { onStep(InstallStep.Download(it)) }
            }

            currentCoroutineContext().ensureActive()
            onStep(InstallStep.Extract)
            TarExtractor.extractSafe(archive, paths.rootfsDir)
        } finally {
            archive.delete()
        }

        currentCoroutineContext().ensureActive()
        onStep(InstallStep.Configure)
        spec.configure(paths.rootfsDir)
        paths.ensureMountPoints()
        validateRootfsIdentity(spec)

        val launcher = launcherFor(spec)
        verifyProotBootstrap(launcher)
        try {
            refreshPackageIndex(spec, launcher)
            currentCoroutineContext().ensureActive()
            installBasePackages(distro, launcher, onStep)
            verifyRequiredCli(distro, launcher)
        } catch (e: Throwable) {
            paths.rootfsDir.deleteRecursively()
            throw e
        }

        val marker = InstallMarker(distro, homeOnRootfs = true)
        paths.writeMarker(marker)
        return marker
    }

    /**
     * The APK-bundled rootfs is Debian-only. The old implementation checked only
     * arm64 and could therefore unpack Debian while installing Ubuntu, producing
     * a marker whose distro did not match the filesystem.
     */
    private fun copyEmbeddedAsset(spec: DistroSpec, target: File): Boolean {
        if (spec.distro != LinuxDistro.DEBIAN) return false
        if (!spec.arch().equals("arm64", ignoreCase = true)) return false
        val assetList = appContext.assets.list("") ?: emptyArray()
        if (EMBEDDED_ROOTFS_ASSET !in assetList) return false
        target.parentFile?.mkdirs()
        appContext.assets.open(EMBEDDED_ROOTFS_ASSET).use { input ->
            FileOutputStream(target).use { output ->
                val buffer = ByteArray(64 * 1024)
                var bytesRead: Int
                while (input.read(buffer).also { bytesRead = it } != -1) {
                    output.write(buffer, 0, bytesRead)
                }
            }
        }
        return true
    }

    /** Verify the extracted filesystem is the distro we are about to record. */
    private fun validateRootfsIdentity(spec: DistroSpec) {
        val osRelease = File(paths.rootfsDir, "etc/os-release")
        check(osRelease.isFile) { "Rootfs is missing /etc/os-release" }
        val values = runCatching {
            osRelease.readLines()
                .mapNotNull { line ->
                    val idx = line.indexOf('=')
                    if (idx <= 0) null else line.substring(0, idx) to line.substring(idx + 1).trim().trim('"')
                }
                .toMap()
        }.getOrElse { error("Cannot read rootfs identity: ${it.message}") }
        val id = values["ID"]?.lowercase()
        check(id == spec.distro.id) {
            "Rootfs mismatch: requested ${spec.distro.id}, extracted ${id ?: "unknown"}"
        }
        if (spec.distro == LinuxDistro.DEBIAN) {
            val major = values["VERSION_ID"]?.substringBefore('.')
            check(major == "13") {
                "Production rootfs must be Debian 13, found ${values["PRETTY_NAME"] ?: values["VERSION_ID"] ?: "unknown"}"
            }
        }
    }

    /** A rootfs is not usable until PRoot can actually execute its shell. */
    private fun verifyProotBootstrap(launcher: ProotLauncher) {
        val result = launcher.execute(
            command = "command -v sh >/dev/null 2>&1 && printf KAI_PROOT_OK",
            timeoutSeconds = RUNTIME_PROBE_TIMEOUT_SECONDS,
        )
        check(result.success && result.stdout.contains("KAI_PROOT_OK")) {
            "PRoot shell probe failed: ${result.failureDetail()}"
        }
    }

    /**
     * Production Debian needs these commands for the terminal, agent installers,
     * process cancellation and file/network tools. Probe the commands rather than
     * trusting package metadata so a damaged prebuilt rootfs cannot be marked ready.
     */
    private fun verifyRequiredCli(distro: LinuxDistro, launcher: ProotLauncher) {
        if (distro != LinuxDistro.DEBIAN) return
        val required = listOf(
            "bash", "python3", "git", "curl", "wget", "tar", "sha256sum",
            "ps", "pgrep", "pkill", "jq", "rg", "ssh", "rsync", "file",
        )
        val command = buildString {
            append("missing=''; ")
            append("for c in ")
            append(required.joinToString(" "))
            append("; do command -v \"$c\" >/dev/null 2>&1 || missing=\"$missing $c\"; done; ")
            append("[ -z \"$missing\" ] || { echo \"missing:$missing\" >&2; exit 127; }; ")
            append("test \"$(dpkg --print-architecture 2>/dev/null)\" = arm64; ")
            append("printf KAI_CLI_OK")
        }
        val result = launcher.execute(command, timeoutSeconds = RUNTIME_PROBE_TIMEOUT_SECONDS)
        check(result.success && result.stdout.contains("KAI_CLI_OK")) {
            "Debian CLI health check failed: ${result.failureDetail()}"
        }
    }

    private fun launcherFor(spec: DistroSpec) = ProotLauncher(
        prootPath = paths.prootPath,
        libDir = paths.libDir,
        rootfsPath = paths.rootfsDir.absolutePath,
        tmpPath = paths.tmpDir.absolutePath,
        binds = emptyList(),
        extraArgs = spec.prootArgs,
        env = spec.env,
    )

    private suspend fun refreshPackageIndex(spec: DistroSpec, launcher: ProotLauncher) {
        if (spec.distro == LinuxDistro.DEBIAN && basePackagesAlreadyInstalled(launcher, spec.distro)) {
            return
        }
        val updateCommand = spec.distro.packageManager.updateCommand
        if (spec !is AlpineSpec) {
            val result = launcher.execute(updateCommand, timeoutSeconds = UPDATE_TIMEOUT_SECONDS)
            check(result.success) { "`$updateCommand` failed: ${result.failureDetail()}" }
            return
        }
        var lastDetail = ""
        for (mirror in spec.mirrors) {
            currentCoroutineContext().ensureActive()
            spec.writeRepositories(paths.rootfsDir, mirror)
            val result = launcher.execute(updateCommand, timeoutSeconds = 60)
            if (result.success) return
            lastDetail = result.failureDetail()
        }
        val suffix = if (lastDetail.isNotEmpty()) ": $lastDetail" else ""
        error("`$updateCommand` failed on all Alpine mirrors$suffix")
    }

    private fun basePackagesAlreadyInstalled(launcher: ProotLauncher, distro: LinuxDistro): Boolean {
        val dpkgStatus = File(paths.rootfsDir, "var/lib/dpkg/status")
        if (!dpkgStatus.exists()) return false
        return try {
            val status = dpkgStatus.readText()
            distro.basePackages.all { pkg ->
                status.contains("Package: $pkg") &&
                    status.substringAfter("Package: $pkg")
                        .substringBefore("\n\n")
                        .contains("install ok installed")
            }
        } catch (_: Exception) {
            false
        }
    }

    private suspend fun installBasePackages(
        distro: LinuxDistro,
        launcher: ProotLauncher,
        onStep: (InstallStep) -> Unit,
    ) {
        if (distro == LinuxDistro.DEBIAN && basePackagesAlreadyInstalled(launcher, distro)) {
            onStep(InstallStep.Packages(distro.basePackages))
            return
        }
        val manager = distro.packageManager
        if (distro == LinuxDistro.ALPINE) {
            for (pkg in distro.basePackages) {
                currentCoroutineContext().ensureActive()
                onStep(InstallStep.Packages(listOf(pkg)))
                val result = launcher.execute(
                    manager.installCommand(pkg),
                    timeoutSeconds = PACKAGE_TIMEOUT_SECONDS,
                )
                check(result.success) { "Failed to install $pkg: ${result.failureDetail(200)}" }
            }
            return
        }
        onStep(InstallStep.Packages(distro.basePackages))
        val result = launcher.execute(
            manager.installCommand(distro.basePackages.joinToString(" ")),
            timeoutSeconds = PACKAGE_TIMEOUT_SECONDS,
        )
        check(result.success) { "Failed to install base packages: ${result.failureDetail()}" }
    }

    companion object {
        /** Serializes package work across features sharing one rootfs. */
        val packageLock = Mutex()
    }
}
